---
# tasks file for rhel-light-update
- name: Generates excluded packages list
  ansible.builtin.set_fact:
    excluded_packages: "{{ hostvars[inventory_hostname]['excluded'] + excluded }}"
    
- name: Print test
  ansible.builtin.debug:
    msg: "{{ excluded_packages }}"

- ansible.builtin.fail:

- name: Ensures that yum-utils is installed
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Ensures that packages are updated
  register: result
  ansible.builtin.yum:
    name: '*'
    state: latest
    security: yes
    exclude: "{{ excluded | join(',') }}"

- name: Check if core libraries where updated
  block:
    - name: Fails if reboot is required
      register: reboot_needed
      changed_when: false
      failed_when: "'Reboot is required' in reboot_needed['stdout']"
      ansible.builtin.command: needs-restarting -r

  rescue:
    - ansible.builtin.debug:
        msg: "Reboot is required, please check ASAP."

- name: Check if services must be restarted
  register: services_to_restart
  changed_when: services_to_restart['stdout'] | length > 0
  ansible.builtin.command: needs-restarting -s
  notify: Restart services
