---
# tasks file for rhel-light-update
- ansible.builtin.set_fact: excluded_packages="{{ hostvars[inventory_hostname]['host_excluded'] + group_excluded + general_excluded }}"
  when: hostvars[inventory_hostname]['host_excluded'] is defined and group_excluded is defined

- ansible.builtin.set_fact: excluded_packages="{{ hostvars[inventory_hostname]['host_excluded'] + general_excluded }}"
  when: hostvars[inventory_hostname]['host_excluded'] is defined and group_excluded is not defined

- ansible.builtin.set_fact: excluded_packages="{{ group_excluded + general_excluded }}"
  when: hostvars[inventory_hostname]['host_excluded'] is not defined and group_excluded is defined

- ansible.builtin.set_fact: excluded_packages="{{ general_excluded }}"
  when: hostvars[inventory_hostname]['host_excluded'] is not defined and group_excluded is not defined
 
- name: Ensures that yum-utils is installed
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: Ensures that packages are updated
  register: result
  ansible.builtin.yum:
    name: '*'
    state: latest
    security: yes
    exclude: "{{ excluded_packages | join(',') }}"

- name: Check if core libraries where updated
  block:
    - name: Fails if reboot is required
      register: reboot_needed
      changed_when: false
      failed_when: "'Reboot is required' in reboot_needed['stdout']"
      ansible.builtin.command: needs-restarting -r

  rescue:
    - ansible.builtin.debug:
        msg: "Reboot is required, please check ASAP."

- name: Check if services must be restarted
  register: services_to_restart
  changed_when: services_to_restart['stdout'] | length > 0 and 'Updating Subscription Management repositories.' not in services_to_restart['stdout']
  ansible.builtin.command: needs-restarting -s
  notify: Restart services
